# Generated by Django 6.0a1 on 2025-09-22 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonesapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phones',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='phones',
            name='properties',
            field=models.CharField(max_length=30),
        ),
    ]
