# Generated by Django 6.0a1 on 2025-09-24 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonesapp', '0002_alter_phones_name_alter_phones_properties'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phones',
            old_name='properties',
            new_name='color',
        ),
        migrations.AddField(
            model_name='phones',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
