# Generated by Django 6.0a1 on 2025-09-24 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phonesapp', '0003_rename_properties_phones_color_phones_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phones',
            name='price',
        ),
    ]
