# Generated by Django 6.0a1 on 2025-09-24 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phonesapp', '0004_remove_phones_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phones',
            old_name='color',
            new_name='properties',
        ),
    ]
