# Generated by Django 6.0a1 on 2025-09-24 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phonesapp', '0005_rename_color_phones_properties'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phones',
            old_name='properties',
            new_name='color',
        ),
    ]
