# Generated by Django 6.0a1 on 2025-09-24 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonesapp', '0006_rename_properties_phones_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='phones',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
