# Generated by Django 6.0a1 on 2025-09-24 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonesapp', '0007_phones_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('property', models.CharField(max_length=100)),
            ],
        ),
    ]
