# Generated by Django 6.0a1 on 2025-10-16 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonesapp', '0009_alter_mainspec_id_alter_phones_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainspec',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='phones',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
