# Generated by Django 6.0a1 on 2025-10-16 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phonesapp', '0010_alter_mainspec_id_alter_phones_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mainspec',
            old_name='name',
            new_name='name2',
        ),
        migrations.RenameField(
            model_name='phones',
            old_name='name',
            new_name='name1',
        ),
    ]
