# Generated by Django 6.0a1 on 2025-10-16 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phonesapp', '0011_rename_name_mainspec_name2_rename_name_phones_name1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mainspec',
            old_name='name2',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='phones',
            old_name='name1',
            new_name='name',
        ),
    ]
