# Generated by Django 6.0a1 on 2025-10-16 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonesapp', '0012_rename_name2_mainspec_name_rename_name1_phones_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainspec',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='mainspec',
            name='property',
            field=models.CharField(max_length=255),
        ),
    ]
